- id: docstrfmt
  name: docstrfmt
  description: "docstrfmt: reStructuredText Formatter"
  entry: docstrfmt
  language: python
  language_version: python3
  minimum_pre_commit_version: 2.9.2
  types_or: [python, rst]